### ISSUE TITLE
Epilogue "cannot be resolved or is not a field"

### ISSUE THREAD

**Issue by zeroClearAmerican** [FRCTeam31/Tchaikovsky_2025Revamp#3]
No build errors, proper usage of Epilogue annotation logging, but during simulation this error is encountered:

```
Error at frc.robot.RobotLogger.update(RobotLogger.java:29): Unhandled exception: java.lang.Error: Unresolved compilation problem: 
        containerLogger cannot be resolved or is not a field

        at frc.robot.RobotLogger.update(RobotLogger.java:29)
        at frc.robot.RobotLogger.update(RobotLogger.java:1)
        at edu.wpi.first.epilogue.logging.ClassSpecificLogger.tryUpdate(ClassSpecificLogger.java:64)
        at edu.wpi.first.epilogue.Epilogue.update(Epilogue.java:34)
        at edu.wpi.first.epilogue.Epilogue.lambda$0(Epilogue.java:55)
        at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:146)
        at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:350)
        at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:418)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by zeroClearAmerican** [comment]
here is a screenshot of the auto-generated RobotLogger class encountering the issue:
![image](https://github.com/user-attachments/assets/a40a0385-b8aa-40ea-8c49-315e2f1e938d)

**Comment by zeroClearAmerican** [comment]
Opened issue in 2025Beta per official recommendation:
https://github.com/wpilibsuite/2025Beta/issues/20

**Comment by zeroClearAmerican** [comment]
Same issue as (this)[https://github.com/wpilibsuite/allwpilib/issues/7103#issuecomment-2439048528]

Workaround is to run the simulation using the command line instead of with the VSCode WPILib command. Using a VSCode terminal window with the command `./gradlew simulateJava` on a Windows machine will successfully start the simulation.

**Comment by zeroClearAmerican** [comment]
Closing due to being a duplicate of https://github.com/wpilibsuite/allwpilib/issues/7103 and having a workaround that allows simulation
